# Generated by Django 2.0.3 on 2018-03-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanYourStudy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Category',
        ),
    ]
