# Generated by Django 2.0.3 on 2018-03-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanYourStudy', '0004_auto_20180330_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Check',
            field=models.BooleanField(default=True),
        ),
    ]
