# Generated by Django 2.0.3 on 2018-03-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanYourStudy', '0006_auto_20180330_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Address',
            new_name='Area',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Check',
        ),
    ]
