# Generated by Django 2.0.3 on 2018-03-24 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.IntegerField(max_length=20)),
                ('DateOfBirth', models.DateField(max_length=8)),
                ('address', models.TextField(max_length=500)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('passport_no', models.IntegerField(max_length=9)),
                ('school', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('marks_highschool', models.IntegerField(max_length=2)),
                ('marks_university', models.IntegerField(max_length=2)),
                ('religion', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrationInfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
