# Generated by Django 2.0.3 on 2018-03-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonregistration',
            name='marks_inter',
            field=models.IntegerField(default='0', max_length=2),
        ),
    ]
