# Generated by Django 2.0.3 on 2018-03-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_commonregistration_marks_inter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonregistration',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='commonregistration',
            old_name='contact',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='commonregistration',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='commonregistration',
            old_name='marks_highschool',
            new_name='Marks_highschool',
        ),
        migrations.RenameField(
            model_name='commonregistration',
            old_name='marks_inter',
            new_name='Marks_inter',
        ),
        migrations.RenameField(
            model_name='commonregistration',
            old_name='marks_university',
            new_name='Marks_university',
        ),
        migrations.RenameField(
            model_name='commonregistration',
            old_name='nationality',
            new_name='Nationality',
        ),
        migrations.RenameField(
            model_name='commonregistration',
            old_name='passport_no',
            new_name='Passport_number',
        ),
        migrations.RenameField(
            model_name='commonregistration',
            old_name='religion',
            new_name='Religion',
        ),
        migrations.RenameField(
            model_name='commonregistration',
            old_name='school',
            new_name='School',
        ),
        migrations.RenameField(
            model_name='commonregistration',
            old_name='university',
            new_name='University',
        ),
    ]
