# Generated by Django 2.0.3 on 2018-03-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180324_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonregistration',
            name='Contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commonregistration',
            name='Marks_highschool',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commonregistration',
            name='Marks_inter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commonregistration',
            name='Marks_university',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commonregistration',
            name='Passport_number',
            field=models.IntegerField(),
        ),
    ]
