# Generated by Django 2.0.3 on 2018-03-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180326_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamGate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('School_12', models.CharField(max_length=30, verbose_name='10th School')),
                ('Marks_10', models.IntegerField(verbose_name='10th Percentage')),
                ('Marks_12', models.IntegerField(verbose_name='12th Percentage')),
                ('School_address', models.CharField(max_length=200, verbose_name='School address')),
                ('School_board', models.CharField(max_length=200, verbose_name='School board')),
                ('University', models.CharField(max_length=100)),
                ('Marks_university', models.IntegerField(verbose_name='University percentage')),
                ('Profile_pic', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='Upload photograph')),
            ],
        ),
        migrations.CreateModel(
            name='ExamJee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('School_12', models.CharField(max_length=30, verbose_name='10th School')),
                ('Marks_10', models.IntegerField(verbose_name='10th Percentage')),
                ('Marks_12', models.IntegerField(verbose_name='12th Percentage')),
                ('School_address', models.CharField(max_length=200, verbose_name='School address')),
                ('School_board', models.CharField(max_length=200, verbose_name='School board')),
                ('Profile_pic', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='Upload photograph')),
            ],
        ),
    ]
